# Generated by Django 5.2.8 on 2025-11-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_align_profile_mood'),
    ]

    operations = [
    ]
