# Generated by Django 5.2.8 on 2025-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_reminder_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
