# Generated by Django 5.2.8 on 2026-02-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sub_tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
