# Generated by Django 5.2.8 on 2026-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurring_type',
            field=models.CharField(blank=True, choices=[('', 'Not Recurring'), ('DAILY', 'Repeat Daily'), ('WEEKLY', 'Repeat Weekly')], default='', max_length=10),
        ),
    ]
