# Generated by Django 5.2.8 on 2026-05-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_todo_is_recurring_todo_last_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='quiz_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='quiz_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='quiz_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='quiz_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='quiz_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='quiz_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='quiz_total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
